### ISSUE TITLE
NPM Requirements

### ISSUE THREAD

**Issue by abkfenris** [willwhitney/jupyter-notebook-atom#1]
You might want to add a list of the npm requirements that it requires installed.

- pathwatcher
- fs-plus
- transformime
- transformime-jupyter-transforme
- uuid
- react
- lodash

I first tried to pip install stuff....

**Comment by willwhitney** [comment]
Oh yeah, you can just run `npm install` and they're all declared in `package.json`.

Added that to readme.

**Comment by rgbkrk** [comment]
Why isn't it `apm install`?

**Comment by willwhitney** [comment]
@rgbkrk this is why I pay you the big bucks
